# Generated by Django 5.0.6 on 2025-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_phone_number_habit_habitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='curr_streak',
            field=models.IntegerField(default=0, verbose_name='Current Streak'),
        ),
    ]
