# Generated by Django 5.0.6 on 2025-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_habit_curr_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(default='12:20:00'),
        ),
    ]
