# Generated by Django 5.0.6 on 2025-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_habit_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(default='18:19:00'),
        ),
    ]
