# Generated by Django 5.0.6 on 2025-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_habit_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
