# Generated by Django 5.0.6 on 2025-03-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_otp_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
