# Generated by Django 5.0.6 on 2025-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_habit_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
