# Generated by Django 5.0.6 on 2025-03-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_habitlog_unique_together_alter_habit_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
    ]
